apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: glpi
  namespace: default
spec:
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 50
          #averageValue: 200Mi  # Ajusta este valor según tus necesidades
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: glpi
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60  # Ajusta este valor según tus necesidades
      policies:
        - type: Pods
          value: 4
          periodSeconds: 30  # Ajusta este valor según tus necesidades
